// src/models/MilkQuality.ts
export interface MilkQuality {
    id?: number;  // Optional since it's auto-generated by the backend
    productionId: number;  // References a milk production entry
    fatContent?: number;  // Percentage, optional
    proteinContent?: number;  // Percentage, optional
    somaticCellCount?: number;  // Number of somatic cells, optional
}
