// src/models/MilkProduction.ts
export interface MilkProduction {
    productionId?: number;  // Optional since it's auto-generated by the backend
    animalId?: number;  // For individual animal entry, optional for whole farm entry
    totalQuantity: string; // Quantity in liters
    productionDate: string;  // Date in 'YYYY-MM-DD' format
    notes?: string;  // Optional notes
}
